---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-12.04


suites:
  - name: default
    run_list: ['role[oracle_java]']
    attributes:
